export const buttons = [
  { id: 'clear', label: 'AC', className: 'col-span-2', type: 'control' },
  { id: 'divide', label: '/', type: 'operator' },
  { id: 'multiply', label: '*', type: 'operator' },
  { id: 'seven', label: '7', type: 'number' },
  { id: 'eight', label: '8', type: 'number' },
  { id: 'nine', label: '9', type: 'number' },
  { id: 'subtract', label: '-', type: 'operator' },
  { id: 'four', label: '4', type: 'number' },
  { id: 'five', label: '5', type: 'number' },
  { id: 'six', label: '6', type: 'number' },
  { id: 'add', label: '+', type: 'operator' },
  { id: 'one', label: '1', type: 'number' },
  { id: 'two', label: '2', type: 'number' },
  { id: 'three', label: '3', type: 'number' },
  { id: 'equals', label: '=', className: 'row-span-2', type: 'equals' },
  { id: 'zero', label: '0', className: 'col-span-2', type: 'number' },
  { id: 'decimal', label: '.', type: 'number' },
];
